config/routes.rb
MusicOnRails::Application.routes.draw do
  get 'music/index', :as => 'select_music'
  get 'listen' => 'music#listen', :as => 'listen_music'
  get 'music/start', :as => 'start_music'
  get 'music/next', :as => 'next_music'
  root :to => 'music#index'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/music_controller.rb
class MusicController < ApplicationController
  def index
  end

  def listen
    # embeds videos
  end

  def start
    # hit YouTube up for a list of videos matching the search
    # randomly pick one
      # ensure that it can be used embeded if not similar
    # set session data
    # if similar, redirect to next
  end

  def next
    # hit audioscrobbler.net for similar artists and bands
    # cache a list to reduce load on their servers
    # send to listen and set session data if HTML
    # if json send cache
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/music_helper.rb
module MusicHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MusicOnRails</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/music/index.html.erb
<%= form_tag(start_music_path) do %>
  <%= label_tag :artist_or_song %>: 
  <%= text_field_tag :search %><br />
  Start with similar artists: <%= check_box_tag :similar %><br />
  <%= submit_tag "Begin the expirence" %>
<% end %>

app/views/music/listen.html.erb
<div id='youtube_video'>&nbsp;</div>

app/views/music/next.html.erb
<h1>Music#next</h1>
<p>Find me in app/views/music/next.html.erb</p>

app/views/music/start.html.erb
<h1>Music#start</h1>
<p>Find me in app/views/music/start.html.erb</p>